import { NextResponse } from 'next/server'

import connectDB from '@/lib/db/mongodb'
import { Product } from '@/lib/models'
import { 
  asyncHandler,
  successResponse} from '@/lib/utils/api-helpers'

// GET - Get single product by ID
export const GET = asyncHandler(async (request, { params }) => {
  try {
    await connectDB()

    const { id } = await params

    const product = await Product.findById(id)
      .select('_id name description category price imageUrl averageRating totalReviews tags isActive createdAt updatedAt')

    if (!product) {
      return NextResponse.json(
        { error: 'Product not found' },
        { status: 404 }
      )
    }

    return successResponse(product)
  } catch (error) {
    console.error('Product API error:', error)
  
    const mockProducts = [
      {
        _id: 'der-wilhelm-1000g',
        name: 'der Wilhelm 1000g',
        nameDe: 'der Wilhelm 1000g',
        slug: 'der-wilhelm-1000g',
        description: 'Traditional rye bread baked on stone according to Grandpa Wilhelm\'s old recipe.',
        descriptionDe: 'Der Wilhelm der Bäckerei Noventa wird nach Opa Wilhelm\'s alter Rezeptur auf Stein gebacken.',
        category: 'brot',
        price: 4.99,
        priceDe: '4,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-wilhelm-der-baeckerei-pappert-wird-nach-opa-wilhelm_s-alter-rezeptur-auf-stein-gebacken.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenbrot', 'Traditional', 'Stone baked'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'das-1928',
        name: 'das 1928',
        nameDe: 'das 1928',
        slug: 'das-1928',
        description: 'Rye mixed bread made with natural sourdough and regional rye.',
        descriptionDe: 'Das 1928 der Bäckerei Noventa aus Natursauerteig und regionalem Roggen.',
        category: 'brot',
        price: 4.49,
        priceDe: '4,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/das-1928-der-baeckerei--aus-natursauerteig-und-regionalem-roggen.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenmischbrot', 'Natural sourdough', 'Regional'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-rubli-dinkler-500g',
        name: 'der Rübli-Dinkler 500g',
        nameDe: 'der Rübli-Dinkler 500g',
        slug: 'der-rubli-dinkler-500g',
        description: 'Spelt bread with carrots, combining carrots, spelt flour and spelt groats with malt flavor.',
        descriptionDe: 'Der Rübli-Dinkler der Bäckerei Noventa mit einer Kombination aus Karotten, Dinkelmehl und Dinkelschrot mit Malzgeschmack.',
        category: 'brot',
        price: 3.99,
        priceDe: '3,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-ruebli-dinkler-der-baeckerei-pappert-mit-einer-kombination-aus-karotten_-dinkelmehl-und-dinkelschrot-mit-malzgeschmack.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Dinkelbrot mit Karotten', 'Spelt', 'Carrots'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-portugiese-500g',
        name: 'der Portugiese 500g',
        nameDe: 'der Portugiese 500g',
        slug: 'der-portugiese-500g',
        description: 'Grill bread filled with paprika, peppers and feta cheese.',
        descriptionDe: 'Der Portugiese der Bäckerei Noventa ist ein Grillbrot mit Hirtenkäse, Paprika und Peperoni gefüllt.',
        category: 'brot',
        price: 4.29,
        priceDe: '4,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-portugiese-der-baeckerei-pappert-ist-ein-grillbrot-mit-paprika-peperoni-und-hirtenkaese-gefuellt.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrot mit Paprika, Peperoni und Hirtenkäse', 'Grill bread', 'Feta'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-wilhelm-mit-kummel-1000g',
        name: 'der Wilhelm mit Kümmel 1000g',
        nameDe: 'der Wilhelm mit Kümmel 1000g',
        slug: 'der-wilhelm-mit-kummel-1000g',
        description: 'Rye bread with caraway seeds, baked on stone according to Grandpa Wilhelm\'s old recipe.',
        descriptionDe: 'Der Wilhelm mit Kümmel der Bäckerei Noventa wird nach Opa Wilhelm\'s alter Rezeptur auf Stein gebacken.',
        category: 'brot',
        price: 5.29,
        priceDe: '5,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-wilhelm-mit-kuemmel-der-baeckerei-pappert-wird-nach-opa-wilhelm_s-alter-rezeptur-auf-stein-gebacken.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenbrot mit Kümmel', 'Caraway', 'Traditional'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'das-nur-750g',
        name: 'das NUR 750g',
        nameDe: 'das NUR 750g',
        slug: 'das-nur-750g',
        description: 'Wheat mixed bread in farmer\'s style, baked on stone.',
        descriptionDe: 'Das Nur der Bäckerei Noventa ist ein Weizenmischbrot nach Bauernart auf Stein gebacken.',
        category: 'brot',
        price: 4.79,
        priceDe: '4,79 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/das-nur-der-baeckerei-pappert-ist-ein-weizenmischbrot-nach-bauernart-auf-stein-gebacken.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenmischbrot', 'Farmer style', 'Stone baked'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'rusti-l-500g',
        name: 'Rusti L 500g',
        nameDe: 'Rusti L 500g',
        slug: 'rusti-l-500g',
        description: 'Rustic rye mixed bread baked on stone.',
        descriptionDe: 'Das Rusti L der Bäckerei Noventa ist ein rustikales auf Stein gebackenes Roggenmischbrot.',
        category: 'brot',
        price: 3.99,
        priceDe: '3,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/das-rusti-l-der-baeckerei-pappert-ist-ein-rustikales-auf-stein-gebackenes-roggenmischbrot.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenmischbrot', 'Rustic', 'Stone baked'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-rogger-500g',
        name: 'der Rogger 500g',
        nameDe: 'der Rogger 500g',
        slug: 'der-rogger-500g',
        description: 'Rye whole grain bread made with finest rye flour from the region.',
        descriptionDe: 'Der Rogger der Bäckerei Noventa aus feinstem Roggenmehl aus der Region.',
        category: 'brot',
        price: 4.49,
        priceDe: '4,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-rogger-der-baeckerei-pappert-aus-feinstem-roggenmehl-aus-der-region.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenvollkornbrot', 'Whole grain', 'Regional'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-roggen-dinkler-750g',
        name: 'der Roggen-Dinkler 750g',
        nameDe: 'der Roggen-Dinkler 750g',
        slug: 'der-roggen-dinkler-750g',
        description: 'Rye-spelt mixed bread with oil seeds, characterized by juicy crumb and long freshness.',
        descriptionDe: 'Der Roggen-Dinkler der Bäckerei Noventa zeichnet sich durch eine saftige Krume und lange Verzehrfrische aus.',
        category: 'brot',
        price: 5.49,
        priceDe: '5,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-roggen-dinkler-der-baeckerei-pappert-zeichnet-sich-durch-eine-saftige-krume-und-lange-verzehrfrische-aus.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggen-Dinkelmischbrot mit Ölsamen', 'Juicy crumb', 'Long freshness'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-dinkler-500g',
        name: 'der Dinkler 500g',
        nameDe: 'der Dinkler 500g',
        slug: 'der-dinkler-500g',
        description: 'Spelt whole grain bread with sunflower seeds, offering many nutrients and long freshness.',
        descriptionDe: 'Der Dinkler der Bäckerei Noventa bietet viele Nährstoffe und eine lange Verzerhrfrische.',
        category: 'brot',
        price: 4.29,
        priceDe: '4,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-dinkler-der-baeckerei-pappert-bietet-viele-naehrstoffe-und-eine-lange-verzehrfrische.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Dinkelvollkornbrot mit Sonnenblumenkernen', 'Nutritious', 'Sunflower seeds'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'rusti-xl-mit-kummel-1000g',
        name: 'Rusti XL mit Kümmel 1000g',
        nameDe: 'Rusti XL mit Kümmel 1000g',
        slug: 'rusti-xl-mit-kummel-1000g',
        description: 'Rustic rye mixed bread with caraway seeds, baked on stone.',
        descriptionDe: 'Das Rusti XL mit Kümmel der Bäckerei Noventa ist ein rustikales auf Stein gebackenes Roggenmischbrot.',
        category: 'brot',
        price: 5.99,
        priceDe: '5,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/das-rusti-xl-mit-kuemmel-der-baeckerei-pappert-ist-ein-rustikales-auf-stein-gebackenes-roggenmischbrot.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenmischbrot mit Kümmel', 'Rustic', 'Caraway'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-franzose-400g',
        name: 'der Franzose 400g',
        nameDe: 'der Franzose 400g',
        slug: 'der-franzose-400g',
        description: 'Wheat bread, also available as point-fresh bread.',
        descriptionDe: 'Der Franzose der Bäckerei Noventa ist auch als punktfrisch-Brot erhältlich.',
        category: 'brot',
        price: 3.49,
        priceDe: '3,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-franzose-der-baeckerei-pappert-ist-auch-als-punktfrisch-brot-erhaeltlich.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrot', 'Point-fresh', 'Wheat'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'der-italiener-500g',
        name: 'der Italiener 500g',
        nameDe: 'der Italiener 500g',
        slug: 'der-italiener-500g',
        description: 'The grill companion with Italian flair.',
        descriptionDe: 'Der Italiener der Bäckerei Noventa ist der Grillbegleiter mit italienischer Note.',
        category: 'brot',
        price: 4.19,
        priceDe: '4,19 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/der-italiener-der-baeckerei-pappert-ist-der-grillbegleiter-mit-italienischer-note.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrot', 'Grill companion', 'Italian'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'rhoner-kruste-750g',
        name: 'Rhöner Kruste 750g',
        nameDe: 'Rhöner Kruste 750g',
        slug: 'rhoner-kruste-750g',
        description: 'Rye mixed bread with ground caraway, gets its original taste thanks to the special grain.',
        descriptionDe: 'Die Rhöner Kruste der Bäckerei Noventa bekommt ihren ursprünglichen Geschmack auch dank der besonderen Körnung.',
        category: 'brot',
        price: 4.99,
        priceDe: '4,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/die-rhoener-kruste-der-baeckerei-pappert-bekommt-seinen-urspruenglichen-geschmack-auch-dank-seiner-besonderen-koernung.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenmischbrot mit gemahlenem Kümmel', 'Special grain', 'Original taste'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'rhoner-korn-750g',
        name: 'Rhöner Korn 750g',
        nameDe: 'Rhöner Korn 750g',
        slug: 'rhoner-korn-750g',
        description: 'Rye mixed bread with seeds, gets its special taste through roasted seeds.',
        descriptionDe: 'Das Rhöner Korn der Bäckerei Noventa erhält seinen besonderen Geschmack durch geröstete Saaten.',
        category: 'brot',
        price: 5.29,
        priceDe: '5,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/brot/das-rhoener-korn-der-baeckerei-pappert-erhaelt-seinen-besonderen-geschmack-durch-geroestete-saaten.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenmischbrot mit Saaten', 'Roasted seeds', 'Special taste'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
    
    
      {
        _id: 'mohnbroetchen',
        name: 'Mohnbrötchen',
        nameDe: 'Mohnbrötchen',
        slug: 'mohnbrotchen',
        description: 'Poppy seed rolls sprinkled with finest poppy seeds.',
        descriptionDe: 'Das Mohnbrötchen der Bäckerei Noventa wird mit feinstem Mohn bestreut.',
        category: 'broetchen',
        price: 1.19,
        priceDe: '1,19 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-mohnbroetchen-der-baeckerei-pappert-wird-mit-feinstem-mohn-bestreut.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Mohnbrötchen', 'Poppy', 'Finest'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'das-handwerk',
        name: 'das Handwerk',
        nameDe: 'das Handwerk',
        slug: 'das-handwerk',
        description: 'Wheat rolls that impress with long freshness.',
        descriptionDe: 'Das Handwerk der Bäckerei Noventa begeistert durch eine lange Frischhaltung.',
        category: 'broetchen',
        price: 0.99,
        priceDe: '0,99 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-handwerk-der-baeckerei-pappert-begeistert-durch-eine-lange-frischhaltung.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen', 'Long freshness', 'Handcrafted'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'feuerhandwerk',
        name: 'Feuerhandwerk',
        nameDe: 'Feuerhandwerk',
        slug: 'feuerhandwerk',
        description: 'Wheat rolls refined with salt-pepper paste.',
        descriptionDe: 'Das Feuerhandwerk der Bäckerei Noventa wird mit Pfeffer verfeinert.',
        category: 'broetchen',
        price: 1.29,
        priceDe: '1,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-feuerhandwerk-der-baeckerei-pappert-wird-mit-mit-pfeffer-verfeinert.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen mit Salz-Pfeffer Paste', 'Refined', 'Pepper'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'roggenbroetchen',
        name: 'Roggenbrötchen',
        nameDe: 'Roggenbrötchen',
        slug: 'roggenbrotchen',
        description: 'Rye rolls made with regional rye from Hessen and Bavaria.',
        descriptionDe: 'Das Roggenbrötchen der Bäckerei Noventa aus regionalem Roggen aus Hessen und Bayern.',
        category: 'broetchen',
        price: 1.09,
        priceDe: '1,09 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-roggenbroetchen-der-baeckerei-pappert-aus-regionalem-roggen-aus-hessen-und-bayern.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Roggenbrötchen', 'Regional', 'Hessen Bavaria'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'ciabattabroetchen',
        name: 'Ciabattabrötchen',
        nameDe: 'Ciabattabrötchen',
        slug: 'ciabattabrotchen',
        description: 'Ciabatta rolls baked with soft dough guidance, olive oil and spices.',
        descriptionDe: 'Das Ciabattabrötchen der Bäckerei Noventa wird mit einer weichen Teigführung, Olivenöl und Gewürzen gebacken.',
        category: 'broetchen',
        price: 1.39,
        priceDe: '1,39 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-ciabattabroetchen-der-baeckerei-pappert-wird-mit-einer-weichen-teigfuehrung_-olivenoel-und-gewuerzen-gebacken.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen', 'Olive oil', 'Spices'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'das-knusprige',
        name: 'das Knusprige',
        nameDe: 'das Knusprige',
        slug: 'das-knusprige',
        description: 'A particularly crispy roll with a crunchy texture.',
        descriptionDe: 'Das Knusprige der Bäckerei Noventa ist ein besonders knackiges Brötchen.',
        category: 'broetchen',
        price: 1.19,
        priceDe: '1,19 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-knusprige-der-baeckerei-pappert-ist-besonders-knackig.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen', 'Crispy', 'Crunchy'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'kaesebroetchen',
        name: 'Käsebrötchen',
        nameDe: 'Käsebrötchen',
        slug: 'kasebrotchen',
        description: 'Wheat rolls with cheese topping.',
        descriptionDe: 'Das Käsebrötchen der Bäckerei Noventa.',
        category: 'broetchen',
        price: 1.49,
        priceDe: '1,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-kaesebroetchen-der-baeckerei-pappert.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen mit Käse überbacken', 'Cheese', 'Topped'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'krusti',
        name: 'Krusti',
        nameDe: 'Krusti',
        slug: 'krusti',
        description: 'A rustic wheat roll with a crispy crust.',
        descriptionDe: 'Das Krusti der Bäckerei Noventa ist ein rustikales Weizenbrötchen mit knackiger Kruste.',
        category: 'broetchen',
        price: 1.29,
        priceDe: '1,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-krusti-der-baeckerei-pappert-ist-ein-rustikales-weizenbroetchen-mit-knackiger-kruste.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen', 'Rustic', 'Crispy crust'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'sonnenblumkernbroetchen',
        name: 'Sonnenblumkernbrötchen',
        nameDe: 'Sonnenblumkernbrötchen',
        slug: 'sonnenblumkernbrotchen',
        description: 'Wheat rolls with sunflower seeds, gets its nutty taste through roasted seeds.',
        descriptionDe: 'Das Sonnenblumenkernbrötchen der Bäckerei Noventa erhält durch geröstete Saaten seinen kernig-nussigen Geschmack.',
        category: 'broetchen',
        price: 1.39,
        priceDe: '1,39 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-sonnenblumenkernbroetchen-der-baeckerei-pappert-erhaelt-durch-geroestete-saaten-seinen-kernig-nussigen-geschmack.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen mit Sonnenblumenkernen', 'Sunflower seeds', 'Roasted'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'sesambroetchen',
        name: 'Sesambrötchen',
        nameDe: 'Sesambrötchen',
        slug: 'sesambrotchen',
        description: 'Sesame rolls sprinkled with finest sesame.',
        descriptionDe: 'Das Sesambrötchen der Bäckerei Noventa wird mit feinstem Sesam bestreut.',
        category: 'broetchen',
        price: 1.19,
        priceDe: '1,19 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-sesambroetchen-der-baeckerei-pappert-wird-mit-feinstem-sesam-bestreut.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Sesambrötchen', 'Sesame', 'Finest'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'salzstange',
        name: 'Salzstange',
        nameDe: 'Salzstange',
        slug: 'salzstange',
        description: 'Wheat pastry with a strong taste thanks to its unmistakable salt-cumin mixture.',
        descriptionDe: 'Die Salzstange der Bäckerei Noventa hat einen kräftigen Geschmack dank ihrer unverkennbaren Salz-Kümmel-Mischung.',
        category: 'broetchen',
        price: 0.89,
        priceDe: '0,89 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/die-salzstange-der-baeckerei-pappert-hat-einen-kraeftigen-geschmack-dank-ihrer-unverkennbaren-salz-kuemmel-mischung.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizengebäck', 'Salt-cumin', 'Strong taste'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'dinkel-krusti',
        name: 'Dinkel-Krusti',
        nameDe: 'Dinkel-Krusti',
        slug: 'dinkel-krusti',
        description: 'Spelt rolls made with spelt flour and spelt whole grain flour.',
        descriptionDe: 'Das Dinkelkrusti der Bäckerei Noventa wird mit Dinkelmehl und Dinkelvollkormehl hergestellt.',
        category: 'broetchen',
        price: 1.49,
        priceDe: '1,49 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-dinkelkrusti-der-baeckerei-pappert-wird-mit-dinkelmehl-und-dinkelvollkornmehl-hergestellt-und-damit-ein-sehr-ballaststoffreiches-dinkelbroetchen.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Dinkelbrötchen', 'Spelt flour', 'Whole grain'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'dreisaatbroetchen',
        name: 'Dreisaatbrötchen',
        nameDe: 'Dreisaatbrötchen',
        slug: 'dreisaatbrotchen',
        description: 'Wheat rolls with seeds, gets its nutty taste through roasted seeds.',
        descriptionDe: 'Das Dreisaatbrötchen der Bäckerei Noventa erhält durch geröstete Saaten seinen kernig-nussigen Geschmack.',
        category: 'broetchen',
        price: 1.39,
        priceDe: '1,39 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-dreisaatbroetchen-der-baeckerei-pappert-erhaelt-durch-geroestete-saaten-seinen-kernig-nussigen-geschmack.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen mit Saaten', 'Seeds', 'Roasted'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'papperz',
        name: 'Papperz',
        nameDe: 'Papperz',
        slug: 'papperz',
        description: 'Wheat rolls with an unmistakable taste and crispy crust.',
        descriptionDe: 'Das Papperz der Bäckerei Noventa hat einen unverwechselbaren Geschmack und eine knackige Kruste.',
        category: 'broetchen',
        price: 1.29,
        priceDe: '1,29 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-papperz-der-baeckerei-pappert-hat-einen-unverwechselbaren-geschmack-und-knackige-kruste.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen', 'Unmistakable', 'Crispy'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'kurbisfit',
        name: 'KürbisFit',
        nameDe: 'KürbisFit',
        slug: 'kurbisfit',
        description: 'Wheat rolls with pumpkin seeds and carrots, baked with Styrian pumpkin seed oil and fresh carrots.',
        descriptionDe: 'Das KürbisFit der Bäckerei Noventa wird mit steirischem Kürbiskernöl und frischen Karotten gebacken.',
        category: 'broetchen',
        price: 1.59,
        priceDe: '1,59 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-kuerbisfit-der-baeckerei-pappert-wird-mit-steirischem-kuerbiskernoel-und-frischen-karotten-gebacken.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Weizenbrötchen mit Kürbiskernen und Karotten', 'Pumpkin seeds', 'Carrots'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'kornspitz-kummel-salz',
        name: 'Kornspitz Kümmel/Salz',
        nameDe: 'Kornspitz Kümmel/Salz',
        slug: 'kornspitz-kummel-salz',
        description: 'A rustic classic with South Tyrolean spice note, made with caraway and salt.',
        descriptionDe: 'Das Kornspitz mit Kümmel und Salz der Bäckerei Noventa ist ein rustikaler Klassiker mit Südtiroler Gewürznote.',
        category: 'broetchen',
        price: 1.69,
        priceDe: '1,69 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-kornspitz-mit-kuemmel-und-salz-der-baeckerei-pappert-ist-ein-rustikaler-klassiker-mit-suedtiroler-gewuerznote.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Kornspitz Kümmel/Salz', 'Rustic', 'South Tyrolean'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
      {
        _id: 'kornspitz-natur',
        name: 'Kornspitz natur',
        nameDe: 'Kornspitz natur',
        slug: 'kornspitz-natur',
        description: 'A rustic classic with South Tyrolean spice note in its natural form.',
        descriptionDe: 'Das Kornspitz Natur der Bäckerei Noventa ist ein rustikaler Klassiker mit Südtiroler Gewürznote.',
        category: 'broetchen',
        price: 1.59,
        priceDe: '1,59 €',
        imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/broetchen/das-kornspitz-natur-der-baeckerei-pappert-ist-ein-rustikaler-klassiker-mit-suedtiroler-gewuerznote.jpg',
        averageRating: 0,
        totalReviews: 0,
        tags: ['Kornspitz natur', 'Natural', 'Classic'],
        isActive: true,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z'
      },
    
    
    
    {
      _id: 'laugenbrezel',
      name: 'Laugenbrezel',
      nameDe: 'Laugenbrezel',
      slug: 'laugenbrezel',
      description: 'Classic pretzel, a traditional German breakfast pastry.',
      descriptionDe: 'Die Laugenbrezel der Bäckerei Noventa ist ein klassisches Laugengebäck.',
      category: 'fruehstuecksgebaeck',
      price: 1.29,
      priceDe: '1,29 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/die-laugenbrezel-der-baeckerei-pappert-ist-ein-klassisches-laugengebaeck.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Laugenbrezel', 'Classic', 'Traditional'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'feuerbrezel',
      name: 'Feuerbrezel',
      nameDe: 'Feuerbrezel',
      slug: 'feuerbrezel',
      description: 'Classic pretzel refined with salt-pepper paste.',
      descriptionDe: 'Die Feuerbrezel der Bäckerei Noventa ist ein klassisches Laugengebäck mit Pfeffer verfeinert.',
      category: 'fruehstuecksgebaeck',
      price: 1.49,
      priceDe: '1,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/die-feuerbrezel-der-baeckerei-pappert-ist-ein-klassisches-laugengebaeck-mit-pfeffer-verfeinert.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Laugenbrezel mit Salz-Pfeffer Paste', 'Refined', 'Pepper'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'buttercroissant',
      name: 'Buttercroissant',
      nameDe: 'Buttercroissant',
      slug: 'buttercroissant',
      description: 'Croissant made with fresh butter.',
      descriptionDe: 'Das Croissant der Bäckerei Noventa wird mit frischer Butter hergestellt.',
      category: 'fruehstuecksgebaeck',
      price: 1.79,
      priceDe: '1,79 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/das-croissant-der-baeckerei-pappert-wird-mit-frischer-butter-hergestellt.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Buttercroissant', 'Fresh butter', 'Classic'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'rosinenbroetchen',
      name: 'Rosinenbrötchen',
      nameDe: 'Rosinenbrötchen',
      slug: 'rosinenbrotchen',
      description: 'Yeast pastry with raisins, baked with high-quality sultanas.',
      descriptionDe: 'Das Rosinenbrötchen der Bäckerei Noventa wird mit hochwertigen Sultaninen gebacken.',
      category: 'fruehstuecksgebaeck',
      price: 1.39,
      priceDe: '1,39 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/das-rosinenbroetchen-der-baeckerei-pappert-wird-mit-hochwertigen-sultaninen-gebacken.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Hefegebäck mit Rosinen', 'High-quality', 'Sultanas'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'milchhoernchen',
      name: 'Milchhörnchen',
      nameDe: 'Milchhörnchen',
      slug: 'milchhornchen',
      description: 'Yeast pastry made with fresh milk from Keinhausen.',
      descriptionDe: 'Das Milchhörnchen der Bäckerei Noventa wird mit frischer Milch aus Keinhausen hergestellt.',
      category: 'fruehstuecksgebaeck',
      price: 1.29,
      priceDe: '1,29 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/das-milchhoernchen-der-baeckerei-pappert-wird-mit-frischer-milch-aus-poppenhausen-hergestellt.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Hefegebäck', 'Fresh milk', 'Keinhausen'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'laugendreieck',
      name: 'Laugendreieck',
      nameDe: 'Laugendreieck',
      slug: 'laugendreieck',
      description: 'Butter pretzel pastry refined with sesame.',
      descriptionDe: 'Das Laugendreieck der Bäckerei Noventa ist ein Butter-Laugengebäck mit Sesam verfeinert.',
      category: 'fruehstuecksgebaeck',
      price: 1.59,
      priceDe: '1,59 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/das-laugendreieck-der-baeckerei-pappert-ist-ein-butter-laugengebaeck-mit-sesam-verfeinert.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['gelaugtes Blätterteiggebäck', 'Butter', 'Sesame'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    
    
    
    {
      _id: 'quarkballchen',
      name: 'Quarkbällchen',
      nameDe: 'Quarkbällchen',
      slug: 'quarkballchen',
      description: 'Quark balls with crispy sugar-cinnamon crust.',
      descriptionDe: 'Die Quarkbällchen der Bäckerei Noventa besitzen eine knusprige Zucker-Zimt-Kruste.',
      category: 'feingebaeck',
      price: 1.19,
      priceDe: '1,19 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/die-quarkbaellchen-der-baeckerei-pappert-besitzen-eine-knusprige-zucker-zimt-kruste.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Siedegebäck', 'Crispy', 'Sugar-cinnamon'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'butterstreuselplatte',
      name: 'Butterstreuselplatte',
      nameDe: 'Butterstreuselplatte',
      slug: 'butterstreuselplatte',
      description: 'Butter yeast pastry topped with delicious crispy streusel.',
      descriptionDe: 'Die Butterstreuselplatte der Bäckerei Noventa wird mit leckeren knackigen Streuseln belegt.',
      category: 'feingebaeck',
      price: 2.49,
      priceDe: '2,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/die-butterstreuselplatte-der-baeckerei-pappert-wird-mit-leckeren-knackigen-streuseln-belegt.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Butter-Hefegebäck mit Butterstreusel', 'Delicious', 'Crispy'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'nussecke',
      name: 'Nussecke',
      nameDe: 'Nussecke',
      slug: 'nussecke',
      description: 'Shortcrust pastry with selected hazelnuts in a delicate shortcrust and chocolate layer.',
      descriptionDe: 'Die Nussecke der Bäckerei Noventa mit ausgewählten Haselnüssen in einem zarten Mürbeteig und Schokoladenschicht.',
      category: 'feingebaeck',
      price: 2.99,
      priceDe: '2,99 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/die-nussecke-der-baeckerei-pappert-mit-ausgewaehlten-haselnuessen-in-einem-zarten-muerbeteig-und-schokoladenschicht.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Mürbeteig mit Haselnüssen und Kuvertüre', 'Selected', 'Hazelnuts'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'spritzring',
      name: 'Spritzring',
      nameDe: 'Spritzring',
      slug: 'spritzring',
      description: 'A great alternative to the classic Kräppel.',
      descriptionDe: 'Der Spritzring der Bäckerei Noventa ist eine tolle Alternative zum klassischen Kräppel.',
      category: 'feingebaeck',
      price: 1.39,
      priceDe: '1,39 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/der-spritzring-der-baeckerei-pappert-ist-eine-tolle-alternative-zum-kraeppel.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Siedebrandgebäck', 'Alternative', 'Classic'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'mohnschnecke',
      name: 'Mohnschnecke',
      nameDe: 'Mohnschnecke',
      slug: 'mohnschnecke',
      description: 'Danish pastry with aromatic poppy seed filling and fine butter taste.',
      descriptionDe: 'Die Mohnschnecke der Bäckerei Noventa mit aromatischer Mohnfüllung und feinem Buttergeschmack.',
      category: 'feingebaeck',
      price: 2.29,
      priceDe: '2,29 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/die-mohnschnecke-der-baeckerei-pappert-mit-aromatischer-mohnfuellung-und-feinem-buttergeschmack.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Plundergebäck mit Mohnfüllung', 'Aromatic', 'Butter taste'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'quarktasche',
      name: 'Quarktasche',
      nameDe: 'Quarktasche',
      slug: 'quarktasche',
      description: 'Danish pastry with quark filling.',
      descriptionDe: 'Die Quarktasche der Bäckerei Noventa ist ein Plundergebäck mit Quarkfüllung.',
      category: 'feingebaeck',
      price: 2.19,
      priceDe: '2,19 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/die-quarktasche-der-baeckerei-pappert-ist-ein-plundergebaeck-mit-quarkfuellung.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Plundergebäck mit Quarkfüllung', 'Quark', 'Danish'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'nussschnecke',
      name: 'Nussschnecke',
      nameDe: 'Nussschnecke',
      slug: 'nussschnecke',
      description: 'Danish pastry made from butter puff pastry with nut filling and fine butter aroma.',
      descriptionDe: 'Die Nussschnecke der Bäckerei Noventa aus Butterplunderteig mit Nussfüllung und feinem Butteraroma.',
      category: 'feingebaeck',
      price: 2.39,
      priceDe: '2,39 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/die-nussschnecke-der-baeckerei-pappert-aus-butterplunderteig-mit-nussfuellung-und-feinem-butteraroma.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Plundergebäck mit Haselnussfüllung', 'Butter puff', 'Nut filling'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'rosinenschnecke',
      name: 'Rosinenschnecke',
      nameDe: 'Rosinenschnecke',
      slug: 'rosinenschnecke',
      description: 'Danish pastry filled with raisins and delicate pudding.',
      descriptionDe: 'Die Rosinenschnecke der Bäckerei Noventa ist gefüllt mit Rosinen und zartem Pudding.',
      category: 'feingebaeck',
      price: 2.29,
      priceDe: '2,29 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/die-rosinenschnecke-der-baeckerei-pappert-ist-gefuellt-mit-rosinen-und-zartem-pudding.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Plundergebäck mit Pudding und Rosinen', 'Raisins', 'Delicate'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'schoko-vanille-croissant',
      name: 'Schoko-Vanille-Croissant',
      nameDe: 'Schoko-Vanille-Croissant',
      slug: 'schoko-vanille-croissant',
      description: 'Puff pastry with vanilla filling and chocolate.',
      descriptionDe: 'Das Schoko-Vanille-Croissant der Bäckerei Noventa besteht aus einem zarten Blätterteig und einer leckeren Schoko-Vanille-Füllung.',
      category: 'feingebaeck',
      price: 2.79,
      priceDe: '2,79 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/fruehstuecksgebaeck/das-schoko-vanille-croissant-der-baeckerei-pappert-besteht-aus-einem-zarten-blaetterteig-und-einer-leckeren-schoko-vanille-fuellung.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Blätterteig mit Vanillefüllung und Schokolade', 'Vanilla', 'Chocolate'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'mohnstriezel',
      name: 'Mohnstriezel',
      nameDe: 'Mohnstriezel',
      slug: 'mohnstriezel',
      description: 'Danish pastry with poppy seed filling and butter streusel, made with regional poppy from Germerode.',
      descriptionDe: 'Der Mohnstriezel der Bäckerei Noventa wird mit regionalem Mohn aus Germerode hergestellt.',
      category: 'feingebaeck',
      price: 2.59,
      priceDe: '2,59 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/feingebaeck/der-mohnstriezel-der-baeckerei-pappert-wird-mit-regionalem-mohn-aus-germerode-hergestellt.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Plundergebäck mit Mohnfüllung und Butterstreusel', 'Regional', 'Germerode'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    
    
    {
      _id: 'rhoner-fladen-mozzarella',
      name: 'Rhöner Fladen Mozzarella',
      nameDe: 'Rhöner Fladen Mozzarella',
      slug: 'rhoner-fladen-mozzarella',
      description: 'Rhöner flatbread with tomato, mozzarella, arugula and pesto.',
      descriptionDe: 'Das Rhöner Fladen Tomate-Mozzarella der Bäckerei Noventa.',
      category: 'snack',
      price: 4.99,
      priceDe: '4,99 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/das-rhoener-fladen-tomate-mozzarella-der-baeckerei-pappert-mit-tomate-mozzarella-sowie-rucola-belegt-und-mit-pesto-bestrichen.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Rhöner Fladen Mozzarella (klein)', 'Tomato', 'Mozzarella'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'rhoner-fladen-haehnchen-gyros',
      name: 'Rhöner Fladen Hähnchen-Gyros',
      nameDe: 'Rhöner Fladen Hähnchen-Gyros',
      slug: 'rhoner-fladen-hahnchen-gyros',
      description: 'Rhöner flatbread with chicken gyros, cabbage, cucumbers and tzatziki.',
      descriptionDe: 'Das Rhöner Fladen Hähnchen-Gyros der Bäckerei Noventa.',
      category: 'snack',
      price: 5.49,
      priceDe: '5,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/der-rhoener-fladen-haehnchen-gyros-der-baeckerei-pappert-mit-haehnchen-gyros-kraut-gurken-und-tsatsiki.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Rhöner Fladen Hähnchen-Gyros', 'Chicken', 'Gyros'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'kaesebroetchen-ei',
      name: 'Käsebrötchen Ei',
      nameDe: 'Käsebrötchen Ei',
      slug: 'kasebrotchen-ei',
      description: 'Wheat rolls with cheese topping and egg.',
      descriptionDe: 'Das Käsebrötchen Ei der Bäckerei Noventa.',
      category: 'snack',
      price: 3.99,
      priceDe: '3,99 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/das-kaesebroetchen-ei-der-baeckerei-pappert.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Weizenbrötchen mit Käse überbacken und mit Ei belegt', 'Cheese', 'Egg'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'teriyaki-bowl',
      name: 'Teriyaki Bowl',
      nameDe: 'Teriyaki Bowl',
      slug: 'teriyaki-bowl',
      description: 'Teriyaki bowl for all fans of Asian cuisine.',
      descriptionDe: 'Die Teriyaki Bowl der Bäckerei Noventa für alle Fans der asiatischen Küche.',
      category: 'snack',
      price: 6.99,
      priceDe: '6,99 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/die-teriyaki-bowl-der-baeckerei-pappert-fuer-alle-fans-der-asiatischen-kueche.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Teriyaki Bowl', 'Asian', 'Cuisine'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'orient-bowl',
      name: 'Orient Bowl',
      nameDe: 'Orient Bowl',
      slug: 'orient-bowl',
      description: 'Orient bowl offers a refreshing exotic alternative.',
      descriptionDe: 'Die Orient Bowl der Bäckerei Noventa bietet eine erfrischend exotische Alternative.',
      category: 'snack',
      price: 6.49,
      priceDe: '6,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/die-orient-bowl-der-baeckerei-pappert-bietet-eine-erfrischend-exotische-alternative.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Orient Bowl', 'Exotic', 'Refreshing'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'rhoner-stulle-pute',
      name: 'Rhöner Stulle Pute',
      nameDe: 'Rhöner Stulle Pute',
      slug: 'rhoner-stulle-pute',
      description: 'Rhöner sandwich with turkey breast and cucumber-mustard spread.',
      descriptionDe: 'Die Rhöner Stulle Pute der Bäckerei Noventa mit Putenbrustfleisch und einem Gurken-Senf-Aufstrich.',
      category: 'snack',
      price: 4.49,
      priceDe: '4,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/die-rhoener-stulle-pute-der-baeckerei-pappert-mit-putenbrustfleisch-und-gurken-senf-aufstrich.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Rhöner Stulle Pute', 'Turkey', 'Mustard'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'rhoner-stulle-vegetarisch',
      name: 'Rhöner Stulle vegetarisch',
      nameDe: 'Rhöner Stulle vegetarisch',
      slug: 'rhoner-stulle-vegetarisch',
      description: 'Rhöner vegetarian sandwich with fresh cheese, spices and crunchy raw vegetable mix.',
      descriptionDe: 'Die Rhöner Stulle vegetarisch der Bäckerei Noventa mit knackigem Rohkostmix belegt sowie Frischkäse und Gewürzen bestrichen.',
      category: 'snack',
      price: 4.29,
      priceDe: '4,29 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/die-rhoener-stulle-vegetarisch-der-baeckerei-pappert-mit-frischkaese-gewuerze-und-einem-knackigem-rohkostmix.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Rhöner Stulle vegetarisch', 'Vegetarian', 'Fresh cheese'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'dreisaat-kaese',
      name: 'Dreisaat Käse',
      nameDe: 'Dreisaat Käse',
      slug: 'dreisaat-kase',
      description: 'Dreisaat cheese, perfect for hearty enjoyment.',
      descriptionDe: 'Das Dreisaat Käse der Bäckerei Noventa.',
      category: 'snack',
      price: 3.79,
      priceDe: '3,79 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/das-dreisaat-kaese-der-baeckerei-pappert-perfekt-fuer-den-herzhaften-genuss.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Dreisaat Käse', 'Hearty', 'Enjoyment'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'papperz-salami',
      name: 'Papperz Salami',
      nameDe: 'Papperz Salami',
      slug: 'papperz-salami',
      description: 'Papperz salami, the popular snack for any time of day.',
      descriptionDe: 'Das Papperz Salami der Bäckerei Noventa.',
      category: 'snack',
      price: 3.99,
      priceDe: '3,99 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/das-papperz-salami-der-baeckerei-pappert-der-beliebte-snack-zu-jeder-tageszeit.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Papperz Salami', 'Popular', 'Any time'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    },
    {
      _id: 'knusperstange',
      name: 'Knusperstange',
      nameDe: 'Knusperstange',
      slug: 'knusperstange',
      description: 'Puff pastry with tomato sauce, bacon and cheese.',
      descriptionDe: 'Die Knusperstange der Bäckerei Noventa mit Tomatensoße, Speck und Käse.',
      category: 'snack',
      price: 3.49,
      priceDe: '3,49 €',
      imageUrl: 'https://www.papperts.de/fileadmin/user_upload/papperts/products/snack/die-knusperstange-der-baeckerei-pappert-mit-tomatensosse-speck-und-kaese.jpg',
      averageRating: 0,
      totalReviews: 0,
      tags: ['Blätterteiggebäck mit Schinken und Käse', 'Bacon', 'Cheese'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z'
    }
    ]

    const { id } = await params
    const mockProduct = mockProducts[id]
    if (mockProduct) {
      return successResponse(mockProduct)
    }

    return NextResponse.json(
      { error: 'Product not found' },
      { status: 404 }
    )
  }
})

// PUT - Update product (admin only)
export const PUT = asyncHandler(async (request, { params }) => {
  try {
    await connectDB()

    const { id } = await params
    const updateData = await request.json()

    const product = await Product.findByIdAndUpdate(
      id,
      updateData,
      { new: true, runValidators: true }
    )

    if (!product) {
      return NextResponse.json(
        { error: 'Product not found' },
        { status: 404 }
      )
    }

    return successResponse(product)
  } catch (error) {
    console.error('Update product error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
})

// DELETE - Delete product (admin only)
export const DELETE = asyncHandler(async (request, { params }) => {
  try {
    await connectDB()

    const { id } = await params

    const product = await Product.findByIdAndDelete(id)

    if (!product) {
      return NextResponse.json(
        { error: 'Product not found' },
        { status: 404 }
      )
    }

    return successResponse({ message: 'Product deleted successfully' })
  } catch (error) {
    console.error('Delete product error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}) 